---
docker_machine_default_version: '0.8.4'
docker_machine_release_api_url: 'https://api.github.com/repos/docker/machine/releases/latest'

docker_apt_keyserver: "hkp://ha.pool.sks-keyservers.net:80"
docker_apt_key_id: 58118E89F3A912897C070ADBF76221572C52609D
docker_apt_url: 'https://apt.dockerproject.org/repo'

docker_debian_dependencies:
- acl
- cgroup-lite
- apparmor
- "linux-image-extra-{{ ansible_kernel }}"
- linux-image-extra-virtual
